### ISSUE TITLE
Unable to decompress the new iOS kernelcache

### ISSUE THREAD

**Issue by brandonplank** [sbingner/kerneldec#1]
In iOS 13.2, apple switched to a new compression format, specifically BVX2. Is it at all possible for you to update kerneldec to support this new kernelcache?

**Comment by sbingner** [comment]
Now it can now but you need the dylib and lzfse.h from https://github.com/sbingner/lzfse - I need to clean up the building stuff to make it simpler

**Comment by brandonplank** [comment]
Have you confirmed the update to this repository to work on 13.2 +? I will test it when I get home.

**Comment by sbingner** [comment]
Of course
