### ISSUE TITLE
Fails on WatchOS 6.2.1 kernelcache

### ISSUE THREAD

**Issue by 0cyn** [sbingner/kerneldec#3]
Repr: `kerneldec -i kernelcache.release.watch3 -o kernelcache.release.watch3.dec`

Output: Invalid input - no lzss magic 0x6276783284b80000

The armv7k (armv7 w/ img4) stuff has been a general pain in the ass, I'll take a look at this myself in a bit.

**Comment by sbingner** [comment]
Issue: krit is retarded
Now resolved.

**Comment by KritantaDev** [comment]
For clarification, the "me being retarded" issue wasn't resolved, unfortunately, but was mitigated by recompiling the library
